---
- name: Instalar paquetes necesarios
  hosts: all
  become: yes

  tasks:
    - name: Actualizar el sistema
      apt:
        update_cache: yes
        upgrade: yes

    - name: Instalar Apache
      apt:
        name: apache2
        state: present

    - name: Instalar MySQL
      apt:
        name: mysql-server
        state: present

    - name: Instalar PHP y módulos
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - php
        - libapache2-mod-php
        - php-mysql
        - php-curl
        - php-gd
        - php-json
        - php-mbstring
        - php-xml
        - php-zip

    - name: Reiniciar Apache
      service:
        name: apache2
        state: restarted

    - name: Habilitar y arrancar MySQL
      service:
        name: mysql
        state: started
        enabled: yes

